[tasks.watch-tailwind]
command = "./tailwindcss"
args = [
  "-m",
  "-c",
  "tailwind.config.js",
  "-i",
  "static/style.css",
  "-o",
  "static/tailwind.css",
  "-w",

]

[tasks.watch-zola]
command = "zola"
args = ["serve"]

[tasks.watch]
run_task = { name = ["watch-zola", "watch-tailwind"], parallel = true }
